galaxy_info:
  author: Goodman Griffin
  description: Corporate Drone working in sector 7 
  company: Castle Computers

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
  - name: Fedora
    versions:
    - all
  - name: RedHat
    versions:
    - all

  galaxy_tags:
  - slack
  - notification

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
