---
# tasks file for yum_updates
# Yum update followed by reboot
# Then compair Kernel versions if different trigger reboot
# Then wait for boxes to come back up by monitoring ssh port connection
#
- name: Perform yum update
  yum: 
    name: "*"
    state: latest
    update_cache: yes
  tags: patch

- name: Compair Kernel versions
  shell: if [ $(rpm -q kernel --queryformat '%{installtime} %{version}-%{release}.%{arch}\n' | sort -n -k1 | tail -1 | cut -d ' ' -f 2) != $(uname -r) ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint
  changed_when: "reboot_hint.stdout == 'reboot'"
  tags: reboot

- set_fact:
    reboot_required: "{% if reboot_hint.stdout == 'reboot' %}true{% else %}false{% endif %}"
    # reboot_required: true  # set this for testing only will force a reboot evertime

# - debug:
#     msg: "Reboot: {{ reboot_required }}"
 
- name: Call Reboot
  include_tasks: reboot.yml
  when: reboot_required
  tags: reboot

