---
# Checks basic connectivity for all hosts both windows and linux
#
#
#
# - hosts: patch_group1
- hosts: patch_now
# - hosts: linux-redis
# - hosts: wiki
# - hosts: prod-monthly
  gather_facts: Yes
  become: yes
#  serial: 3

  roles:
    - yum_updates
    - reboot-server  # only if kernel has been upgraded.

