---
# Checks basic connectivity for all hosts both windows and linux
#
#
#
# - hosts: patch_group1
- hosts: linux-redis
  gather_facts: Yes
  become: yes
  serial: 1

  roles:
    - yum_updates
    - reboot-server  # only if kernel has been upgraded.

