---
# Patch selected host with Yum update and reboot if kernel is updated.
#
#
# (patch_group1 wiki patch_now linux-redis prod-monthly)
# 
- hosts: "{{ variable_host | default('test') }}"
  gather_facts: Yes
  become: yes
#  serial: 3    # used when only wanting to do 3 at a time

  roles:
    - yum_updates
    - reboot-server  # only if kernel has been upgraded.

