---
# Checks basic connectivity for all hosts both windows and linux
#
#
#
- hosts: docker_ee
# - hosts: mysql
  gather_facts: Yes
  become: no

  tasks:

   - name: Check Linux Connections
     setup:

