---
# Checks to make sure all systems that will be patched are available and can connect.
# Use this before patching a group to be sure that all systems are up and functioning.
#
- hosts: "{{ variable_host | default('test') }}"
  gather_facts: Yes
  become: no
  tasks:
   - name: Check Connection
     setup:

