---
linux:
   tower:
      - cvyhj3a21.oai.olympusglobal.com
   wiki:
      - cvyhj3a17v.oai.olympusglobal.com
   datasweep:
      - cvyhj2a60v.oai.olympusglobal.com
      - cvyhj2a61v.oai.olympusglobal.com
      - cvyhj2a62v.oai.olympusglobal.com
      - cvyhj2a63v.oai.olympusglobal.com
   splunk:
      - CVYHJ1A06V.OAI.OLYMPUSGLOBAL.COM
      - CVYHJ3311V.OAI.OLYMPUSGLOBAL.COM
   test:
      - cvyhj2a60v.oai.olympusglobal.com
      - cvyhj3a05v.oai.olympusglobal.com

windows:
   win2008:
      - CVYHJ1A06.OAI.OLYMPUSGLOBAL.COM
      - CVYHJ3A15V.OAI.OLYMPUSGLOBAL.COM
      - CVYHJ3A34V.OAI.OLYMPUSGLOBAL.COM
   scripting:
      - CVYHJ3A15V.OAI.OLYMPUSGLOBAL.COM
   IIsServer:
      - CVYHJ1A06.OAI.OLYMPUSGLOBAL.COM
