---
# Checks ability to send slack messages
# this can be included in modules.
#
#
- hosts: wiki
  gather_facts: Yes
  become: no


  tasks:

#  - name: Slack Notify
#    include_role:
#      name: slack-msg
#    vars:
#      slack_message: "Test Message"
#      slack_channel: "{{ slack_test_channel }}"
#      slack_icon: "{{ slack_icon_fail }}"
#      slack_color: "danger"
#    tags:
#      - slack

  - name: Slack Notify2
    include_role:
      name: slack-msg
    vars:
      slack_message: "Test Message at 11:38"
