---
# Checks ability to send slack messages
# this can be included in modules.
# Changed in latest change for a test
#
- hosts: test
  gather_facts: no
  become: no


  tasks:

  - include_role:
      name: slack-notification
    vars:
      slack_message: "Processing host {{inventory_hostname}}"

