---
# Test.yml
- name: Bring up docker containers for docker connection inventory iface
  hosts: localhost
  roles:
    - role: provision_docker
      provision_docker_privileged: true,
      provision_docker_inventory_group: "{{ groups['robots'] }}"
      provision_docker_use_docker_connection: true
      tags: provision_docker

- hosts: robots
  gather_facts: yes
  become: no


  tasks:

  - include_role:
      name: slack-msg
    vars:
      slack_message: "Processing host {{inventory_hostname}}"
      slack_channel: "{{ slack_test_channel }}"

  - name: Dump Vars
    debug: var=hostvars[inventory_hostname]
   
