---
# Checks basic connectivity for all hosts both windows and linux
#
#
#
- hosts: linux
  gather_facts: Yes
  become: no

  tasks:

   - name: Check Linux Connections
     setup:

- hosts: windows
  gather_facts: Yes
  become: no

  tasks:

   - name: Check Windows Connections
     setup:

