# Create CSR

- debug:
    msg: "Priv_Key {{ Priv_Key }}"

- fail: # Check this one.
    msg: "The private key {{ private_key }} already exist"
  when: Priv_Key

- name: Create san.cnf on server
  template:
    src: san.cnf.j2
    dest: "{{ san_cnf }}"
    mode: '0606'

- name: Create Private Key
  # openssl req -out sslcert.csr -newkey rsa:2048 -nodes -keyout private.key -config san.cnf
  shell:
    cmd: "openssl req -out {{ sslcert_csr }} -newkey rsa:2048 -nodes -keyout {{ private_key }} -config {{ san_cnf }}"
    creates: "{{ sslcert_csr }}"

- name: Create email instructions
  template:
    src: email.txt.j2
    dest: "{{ email_filename }}"
    mode: '0666' 

- name: Send Slack Email
  # uses common slack module in /etc/ansible/roles
  include_role:
    name: slack-msg
  vars:
    slack_message: "{{ email_out }}"
  tags:
    - slack

- name: Get CSR to VAR
  command: "cat {{ sslcert_csr }}"
  register: csr_text

- name: Send Slack CSR record 
  # uses common slack module in /etc/ansible/roles 
  include_role:
    name: slack-msg
  vars:
    slack_message: "{{ lookup('template', 'csr_text.txt.j2') }}"
  tags:
    - slack

