- name: Create PFX
  debug:
    msg: "JOB {{ JOB }}"

- name: Check for Cert file
  stat: 
    path: "{{ cert_filename }}"
  register: cert_result

- set_fact:
    Cert_OK: True
  when: cert_result.stat.exists == True
#
- fail:
    msg: "The cert file not present: {{ cert_filename }}"
  when: not Cert_OK
#
#
- name: Create PFX file
# openssl pkcs12 -export -out tower.oai.olympusglobal.com.pfx -inkey tower.oai.olympusglobal.com.key -in tower.oai.olympusglobal.com.cer
  shell:
    cmd: "openssl pkcs12 -export -out {{ pfx_filename }} -inkey {{ private_key }} -in {{ cert_filename }} -password pass:{{ key_pass }}"
    creates: "{{ pfx_filename }}"
