- name: Delete CSR and Private Key
  # Attempt to delete all entries with this CN
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ sslcert_csr }}"
    - "{{ private_key }}"
    - "{{ san_cnf }}"
    - "{{ email_filename }}"
