--- # tasks file for cert-build
# JOB: (CLEAN, CSR, PFX, UPLOAD)

- set_fact:
    temp_work:  "{{ temp_work }} + ['{{ item }}']"
  with_items: "{{ SAN_names_input.split('\n') }}"

#- debug:
#    msg: "{{ temp_work }}"

- set_fact:
    SAN_name: "{{ temp_work }}"

- name: Check Directories are there
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ base_loc }}"  # base file path ex: /etc/tls/
    - "{{ pending_loc }}"  # added to file path ex: {base_loc}/pending
    - "{{ cert_loc }}"     # storage for certificates
    - "{{ private_loc }}"  # storage for keys



- name: Check if Private Key exists
  # must make sure not to over-write an exsisting private key
  stat:
    path: "{{ private_key }}"
  register: key_result

- set_fact:
    Priv_Key: True
  when: key_result.stat.exists == True
#
# CLEAN
- name: Clean Job
  # Clean out and delete old CSR's and Private Keys
  include_tasks: delete-csr.yaml
  when: JOB == 'CLEAN'
#
# Create new CSR
- name: Create new CSR
  # create csr only if there is not already a Private Key for this CN
  include_tasks: create-csr.yaml
  when: JOB == 'CSR'
#
# Upload New Cert
- name: Upload new Cert
  # Upload a new cert into the correct directory
  include_tasks: upload-cert.yaml
  when: JOB == 'UPLOAD'

- name: Create PFX
  # take cert and private key and make a PFX file
  include_tasks: create-pfx.yaml
  when: JOB == 'PFX'
