# - name: Upload Cert to folder
#   copy:
#     content: "{{ Cert_content }}"
#     dest: "{{ cert_filename }}"
#

- debug:
    msg: "CertLength: {{ Cert_content | length }}"

- assert:
    that:
      - "Cert_content | length > 5"
    msg: "'Cert_content' must have length greater than 5"

- name: Upload Cert to folder
  template:
    src: cert.crt.j2
    dest: "{{ cert_filename }}"
    mode: '0666'
  when: Cert_content.length > 15

- name: Create PFX
  # take cert and private key and make a PFX file
  include_tasks: create-pfx.yaml
  when: Cert_content.length > 15
