# - name: Upload Cert to folder
#   copy:
#     content: "{{ Cert_content }}"
#     dest: "{{ cert_filename }}"
#
- name: Upload Cert to folder
  template:
    src: cert.crt.j2
    dest: "{{ cert_filename }}"
    mode: '0666'
