---
# tasks file for docker

- name: Get Installed Docker Version
  # shell: "docker version --format '{{.Server.Version}}'"
  shell: "docker version --format '{{ '{{' }} .Server.Version {{ '}}' }}'"
  register: version
  changed_when: False
  ignore_errors: yes

- name: Set Fact with Installed Docker Version
  set_fact:
    docker_installed_version: "{{ version.stdout }}"

- name: SetDocker Var
  set_fact:
    docker_ee_installed: True
  when: version.stdout == docker_install_version

- debug:
    var: docker_ee_installed


- name: Docker | EE | Store Docker EE repository URL
  copy:
    content: "{{ docker_ee_url }}"
    dest: /etc/yum/vars/dockerurl
  when: not docker_ee_installed


- name: Docker dockerosversion
  copy:
    content: "{{ docker_dockerosversion }}"
    dest: /etc/yum/vars/dockerosversion
  when: not docker_ee_installed


#  Run this only if we really want to remove Docker in the future
- name: Uninstall old Docker versions
  yum:
    name: "{{ item }}"
    state: removed
  with_items:
     - docker
     - docker-client
     - docker-client-latest
     - docker-common
     - docker-latest
     - docker-latest-logrotate
     - docker-logrotate
     - docker-selinux
     - docker-engine-selinux
     - docker-engine
     - docker-ce
     - docker-ce-selinux
  notify: yum-clean-metadata
  when: not docker_ee_installed

- name: Install Docker required packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
     - yum-utils
     - device-mapper-persistent-data
     - lvm2
  when: not docker_ee_installed

- name: Remove Docker-CE Repo
  # Remove docker-ce.repo
  file:
     path: /etc/yum.repos.d/docker-ce.repo
     state: absent
  when: not docker_ee_installed

- name: Enable extras repo
  shell: yum-config-manager --enable rhel-7-server-extras-rpms
  when: not docker_ee_installed

- name: Add Docker-EE Repo
  shell: yum-config-manager --add-repo "{{ docker_repo_url }}"
  when: not docker_ee_installed

- name: Set Latest Docker Version
  shell: yum-config-manager --enable docker-ee-stable-18.03
  when: not docker_ee_installed

- name: Install Docker-ee
  yum:
    name: docker-ee
    state: installed
  notify: restart-docker
  when: not docker_ee_installed

- name: Start Docker-EE
  service:
    name: docker
    enabled: yes
    state: started

- name: Run Hello-world
  command: docker run hello-world
  register: output_text

- name: Look for Hello from Docker
  # if we don't find the text "Hello from Docker" FAIL
  action: fail
  when: output_text.stdout.find("Hello from Docker!") == -1
