---
# handlers file for docker

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: restart-docker
  service:
    name: docker
    state: restarted

- name: restart sssd
  service: name=sssd state=restarted

