---
# tasks file for docker-files
# Copy misc files for the docker nodes

# Self signed certs for cvyhj1a06v
- name: make docker cert dir cvyhj1a06v
  file: 
    path: "/etc/docker/certs.d/cvyhj1a06v.oai.olympusglobal.com:5000"
    state: directory
    recurse: yes

- name: move cert for node cvyhj1a06v
  copy:
    src: "{{ role_path }}/files/ca.crt"
    dest: /etc/docker/certs.d/cvyhj1a06v.oai.olympusglobal.com:5000/ca.crt

# Certs for kubecluster from internal cert store
- name: make docker cert dir kubecluster
  file:
    path: "/etc/docker/certs.d/kubecluster.oai.olympusglobal.com:8443"
    state: directory
    recurse: yes

- name: move cert for node kubecluster
  copy:
    src: "{{ role_path }}/files/kubecluster.oai.olympusglobal.com.2018.crt"
    dest: /etc/docker/certs.d/kubecluster.oai.olympusglobal.com:8443/client.cert


- name: move key for node kubecluster
  copy:
    src: "{{ role_path }}/files/kubecluster.oai.olympusglobal.com.2018.key"
    dest: /etc/docker/certs.d/kubecluster.oai.olympusglobal.com:8443/client.key


- name: move ca_cert for OlympusGlobal
  copy:
    src: "{{ role_path }}/files/olympusglobal_ca.crt"
    dest: /etc/docker/certs.d/kubecluster.oai.olympusglobal.com:8443/ca.crt



#- name: Update host file for kubecluster
#  lineinfile:
#     path: /etc/hosts
#     regexp: '^10.160.46.88 kubecluster'
#     line: '10.160.46.88 kubecluster.oai.olympusglobal.com kubecluster'



# not used but still nice to try since insecure registries are not appartently working
#
#- name: delete bogus docker.json
#  file:
#    dest: /etc/docker/docker.json
#    state: absent

- name: template docker.json.j2
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
  notify: restart docker




