---
# defaults file for cert-build
# These need to be overwritten by querry

temp_work: []
CN_name: "plasmabutton.com"
SAN_name:
  - plasmabutton.com
  - www.plasmabutton.com

SAN_names_input: |-
  acme.com
  www.acme.com
  test.acme.com

####################### do not change below this line ########

# YEAR
cur_year: "2018"


# file defaults
# key
key_name: "key"
csr_name: "csr"
crt_name: "crt"
pfx_name: "pfx"
# locations
# base_loc: "/etc/pki/tls"  # base location for certs
base_loc: "/tmp"
pending_loc: "{{ base_loc }}/pending"  # pending work directory
cert_loc: "{{ base_loc }}/cert"   # cert stored here
private_loc: "{{ base_loc }}/private"   # key stored here

# Filenames
cur_filename: "{{ CN_name }}.{{ cur_year}}"
sslcert_csr: "{{ pending_loc }}/{{ cur_filename }}.{{ csr_name }}"
private_key: "{{ private_loc }}/{{ cur_filename }}.{{ key_name }}"
san_cnf: "{{ pending_loc }}/{{ cur_filename }}.cnf"

#
# PW subject to change
key_pass: "Olympus2018!!"
