---
# defaults file for cert-build
# These are overwritten by querry from web interface

temp_work: []
Priv_Key: False
Cert_OK: False
Cert_content: ""
#
# CN_name: "donotuse.com"
CN_name: "tower.oai.olympusglobal.com"
SAN_name: []

# Sample default SAN names
SAN_names_input: |-
  www.replace.com
  test.replace.com
#
# JOB: (CLEAN, CSR, PFX, UPLOAD)
# JOB: 'CLEAN'    # Delete CSR and Private Key and config file
JOB: 'CSR'      # Create new CSR
# JOB: 'PFX'      # Generate PFX file
# JOB: 'UPLOAD'   # Upload new Cert to server
#
# Current year this can be overridden here for working on a different year other than current.
cur_year: "{{ lookup('pipe','date +%Y') }}"  # capture current year

####################### do not change below this line ########
# file defaults
# key
key_name: "key"
csr_name: "csr"
crt_name: "crt"
pfx_name: "pfx"
# locations
# base_loc: "/etc/pki/tls"  # base location for certs
base_loc: "/etc/pki/tls/test"
pending_loc: "{{ base_loc }}/pending"  # pending work directory
cert_loc: "{{ base_loc }}/cert"   # cert stored here
private_loc: "{{ base_loc }}/private"   # key stored here
complete_loc: "{{ base_loc }}/complete" # Archive location for completed request

# Filenames
cur_filename: "{{ CN_name }}.{{ cur_year}}"
sslcert_csr: "{{ pending_loc }}/{{ cur_filename }}.{{ csr_name }}"
private_key: "{{ private_loc }}/{{ cur_filename }}.{{ key_name }}"
san_cnf: "{{ pending_loc }}/{{ cur_filename }}.cnf"
pfx_filename: "{{ complete_loc }}/{{ cur_filename }}.{{ pfx_name }}"
cert_filename: "{{ cert_loc }}/{{ cur_filename }}.{{ crt_name }}"
email_filename: "{{ pending_loc }}/{{ cur_filename }}.email.txt"

# Email
email_out: "{{ lookup('template', 'email.txt.j2') }}"
