---
# handlers file for yum_updates
# currently these are not being used
# they are nice things to have in case we need them
#
- name: reboot box
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_hint.stdout == 'reboot'

- name: wait after reboot
  local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=30 timeout=200 connect_timeout=15
  when: reboot_hint.stdout == 'reboot'
