---
# Create user loc_ansible
# Transfer SSH key for user
# Set files mostly templates to support AD logins
#

- name: Create user loc_ansible
  user:
    name: loc_ansible
    append: yes
    shell: /bin/bash
    home: /home/loc_ansible
    password: "{{ loc_ansible_pw | password_hash('sha512', 'secetOlympus2018') }}"
    create_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/loc_ansible/.ssh/id_rsa
    comment: "Ansible System Account"
    groups: wheel
  become: yes

- name: Public key for loc_ansible
  copy:
    src: authorized_keys
    dest: /home/loc_ansible/.ssh/authorized_keys
    mode: 0600
    owner: loc_ansible
    group: loc_ansible
