---
# tasks file for realm_info
# Set files mostly templates to support AD logins
#
#

- name: Call create user
  include_tasks: "create-user.yaml"

- name: Call Update sudoers
  include_tasks: "sudoers-update.yaml"


- name: SetPrompt.sh copy
  template:
    src: set-prompt.sh.j2
    dest: /etc/profile.d/set-prompt.sh
    owner: root
    group: root
    mode: 0555

- name: Install common packages
  yum:
    name: "{{ common_packages }}"
  when: common_packages is defined

- name: Remove excess packages
  yum:
    name: "{{ group_package_remove }}"
  when: group_package_remove is defined

- name: Check for SSSD.conf
  stat:
    path: /etc/sssd/sssd.conf
  register: stat_result

- name: template SSSD.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify: restart sssd
  when: stat_result.stat.exists == True


