---
# tasks file for realm_info
# Set files mostly templates to support AD logins
#
#

- name: Call create user
  include_tasks: "create-user.yaml"
  become: yes
  tags:
     - user

- name: Call Update sudoers
  include_tasks: "sudoers-update.yaml"
  tags:
     - sudoers

- name: Call Yum
  include_tasks: "yum.yaml"
  tags:
     - yum


- name: SetPrompt.sh copy
  template:
    src: set-prompt.sh.j2
    dest: /etc/profile.d/set-prompt.sh
    owner: root
    group: root
    mode: 0555

- name: Check for SSSD.conf
  stat:
    path: /etc/sssd/sssd.conf
  register: stat_result

- name: template SSSD.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify: restart sssd
  when: stat_result.stat.exists == True


