---
# tasks file for docker

# Run this only if we really want to remove Docker in the future
#- name: ensure old docker removed
#  yum:
#    name: "{{ item }}"
#    state: removed
#  with_items:
#     - docker-common
#     - docker-selinux
#     - docker-engine
#  notify: yum-clean-metadata

- name: Update Repo for Docker-CE
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    enabled: yes

- name: Check search-disabled-repos.conf
  lineinfile:
    path: /etc/yum/pluginconf.d/search-disabled-repos.conf
    regexp: '^notify_only='
    line: 'notify_only=0'

- name: Install Docker-CE
  yum:
    name: docker-ce
    state: latest
  notify: restart-docker

- name: Start Docker-CE
  service:
    name: docker
    enabled: yes
    state: started

- name: Run Hello-world
  command: docker run hello-world
  register: output_text

- name: Look for Hello from Docker
  # if we don't find the text "Hello from Docker" FAIL
  action: fail
  when: output_text.stdout.find("Hello from Docker!") == -1

     
  
