---
# tasks file for docker

- name: Get Installed Docker Version
  # shell: "docker version --format '{{.Server.Version}}'"
  shell: "docker version --format '{{ '{{' }} .Server.Version {{ '}}' }}'"
  register: version
  changed_when: False
  ignore_errors: yes

- name: Set Fact with Installed Docker Version
  set_fact:
    docker_installed_version: "{{ version.stdout }}"

- name: SetDocker Var
  set_fact:
    docker_ee_installed: True
  when: version.stdout == docker_install_version

- debug:
    var: docker_ee_installed

# excute only if docker not installed
- name: Install of Docker-EE
  include_tasks: install-docker.yaml
  when: not docker_ee_installed

- name: Start Docker-EE
  service:
    name: docker
    enabled: yes
    state: started

- name: Run Hello-world
  command: docker run hello-world
  register: output_text

- name: Look for Hello from Docker
  # if we don't find the text "Hello from Docker" FAIL
  action: fail
  when: output_text.stdout.find("Hello from Docker!") == -1

- name: Install of docker utils etc
  yum: name={{item}} state=latest
  with_items: "{{ misc_packages }}"
  when: misc_packages is defined

