---
# tasks file for docker

 Run this only if we really want to remove Docker in the future
- name: Uninstall old Docker versions
  yum:
    name: "{{ item }}"
    state: removed
  with_items:
     - docker
     - docker-client
     - docker-client-latest
     - docker-common
     - docker-latest
     - docker-latest-logrotate
     - docker-logrotate
     - docker-selinux
     - docker-engine-selinux
     - docker-engine
     - docker-ce
  notify: yum-clean-metadata

- name: Remove Docker-CE Repo
  # Remove docker-ce.repo
  file:
     path: /etc/yum.repos.d/docker-ce.repo
     state: absent








- name: Update Repo for Docker-CE
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    enabled: yes

- name: Check search-disabled-repos.conf
  lineinfile:
    path: /etc/yum/pluginconf.d/search-disabled-repos.conf
    regexp: '^notify_only='
    line: 'notify_only=0'

#- name: Install Docker-CE
#  yum:
#    name: docker-ce-17.03.2.ce-1.el7.centos.x86_64
#    state: installed
#  notify: restart-docker

- name: Start Docker-CE
  service:
    name: docker
    enabled: yes
    state: started

- name: Run Hello-world
  command: docker run hello-world
  register: output_text

- name: Look for Hello from Docker
  # if we don't find the text "Hello from Docker" FAIL
  action: fail
  when: output_text.stdout.find("Hello from Docker!") == -1

- name: Update REPO for K8s
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0600

#- name: Install K8s
#  yum:
#    name: "{{ item }}"
#    state: installed 
#  with_items:
#     - kubelet
#     - kubeadm
#     - kubectl
